### ISSUE TITLE
Default values for creating crypto accounts

### ISSUE THREAD

**Issue by gregscullard** [launchbadge/hedera-sdk-rust-archived#1]
Default values for sendRecordThreshold and receiveRecordThreshold must be set by the SDK when creating a crypto account. Not setting the sendRecordThreshold will result in its value being 0, and all transfers out of the account will result in a record being created. 

The value should be set to the java equivalent of Long.MAX_VALUE (maximum value of a long).

**Comment by mehcode** [comment]
I'm guessing this needs to be set somewhere around here: https://github.com/hashgraph/hedera-sdk-rust/blob/master/src/transaction.rs#L201

And a `Long` in Java is a `i64` in Rust. The equivalent expression is `i64::max_value()`.

**Comment by gregscullard** [comment]
Yes, body.set...

**Comment by mehcode** [comment]
You can use `cargo doc --document-private-items --open` to generate local documentation for the `proto` module so you can inspect what methods were generated from the protobuf files

**Comment by mehcode** [comment]
All done. Thanks @gregscullard
