### ISSUE TITLE
Rename repo description to "Ħedera SDK for Rust"

### ISSUE THREAD

**Issue by mehcode** [launchbadge/hedera-sdk-rust-archived#34]
//cc @kenthejr @gregscullard

**Comment by QuestofIranon** [comment]
Would this affect searchability?

**Comment by mehcode** [comment]
Repos got keywords that mention Hedera so I don't think so

**Comment by QuestofIranon** [comment]
I was thinking about for example this menu ->

![image](https://user-images.githubusercontent.com/2449351/49602273-ea5b3500-f93c-11e8-8cb1-dc80e5152f5c.png)

**Comment by mehcode** [comment]
That menu is based on repo _name_ not description. The search will consider keywords too.

**Comment by QuestofIranon** [comment]
Oh wait, yeah I was thinking name would be changed instead of description.

**Comment by tim-mchale** [comment]
We don't want to use the Ħ symbol as a letter for branding-related issues, but I have updated the description to "Hedera SDK for Rust"
