### ISSUE TITLE
Cannot compile the hedera-sdk-rust

### ISSUE THREAD

**Issue by orlcp440** [launchbadge/hedera-sdk-rust-archived#57]
Problem: I cannot build hedera-sdk-rust. What steps should I take to do it successfully?

I am running Windows 10 Pro 64bit (ver 10.0.17134 Build 17134) on an XPS 15 9530 Laptop with 16GB of RAM. The folowing are the steps I am taking.

1) Open a command prompt and go to my user folder (ex C:\Users\Orlando)
2) Download rustup-init.exe from https://rustup.rs/ and put it in my user folder
3) From the console I run rustup-init.exe --default-host x86_64-pc-windows-msvc --default-toolchain nightly-2018-12-15 (I got the toolchain to use from hedera-sdk-rust rust-toolchain file)
4) In the menu that appears I choose number 1 and hit enter and it installs rustup and rustc etc
5) Download the rust SDK by doing git clone --recursive https://github.com/hashgraph/hedera-sdk-rust.git
3) cd into the hedera-sdk-rust directory that the git clone command created
4) type "cargo build" and see it fail while building
5) I have pasted the whole process and the resulting error below

//-----------------------------------------------

C:\Users\Orlando>rustup-init.exe --default-host x86_64-pc-windows-msvc --default-toolchain nightly-2018-12-15

Welcome to Rust!

This will download and install the official compiler for the Rust programming
language, and its package manager, Cargo.

It will add the cargo, rustc, rustup and other commands to Cargo's bin
directory, located at:

  C:\Users\Orlando\.cargo\bin

This path will then be added to your PATH environment variable by modifying the
HKEY_CURRENT_USER/Environment/PATH registry key.

You can uninstall at any time with rustup self uninstall and these changes will
be reverted.

Current installation options:

   default host triple: x86_64-pc-windows-msvc
     default toolchain: nightly-2018-12-15
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: syncing channel updates for 'nightly-2018-12-15-x86_64-pc-windows-msvc'
info: latest update on 2018-12-15, rust version 1.33.0-nightly (96d1334e5 2018-12-14)
info: downloading component 'rustc'
 56.1 MiB /  56.1 MiB (100 %)  25.9 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 50.1 MiB /  50.1 MiB (100 %)  26.3 MiB/s ETA:   0 s
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: default toolchain set to 'nightly-2018-12-15'

  nightly-2018-12-15 installed - rustc 1.33.0-nightly (96d1334e5 2018-12-14)

Rust is installed now. Great!

To get started you need Cargo's bin directory (%USERPROFILE%\.cargo\bin) in
your PATH environment variable. Future applications will automatically have the
correct environment, but you may need to restart your current shell.

Press the Enter key to continue.

C:\Users\Orlando>exit

Microsoft Windows [Version 10.0.17134.472]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\Users\Orlando

C:\Users\Orlando>
C:\Users\Orlando>
C:\Users\Orlando>rustup show
Default host: x86_64-pc-windows-msvc

nightly-2018-12-15-x86_64-pc-windows-msvc (default)
rustc 1.33.0-nightly (96d1334e5 2018-12-14)

C:\Users\Orlando>
C:\Users\Orlando>rustup --version
rustup 1.16.0 (beab5ac2b 2018-12-06)

C:\Users\Orlando>rustc --version
rustc 1.33.0-nightly (96d1334e5 2018-12-14)

C:\Users\Orlando>cargo --version
cargo 1.33.0-nightly (2cf1f5dda 2018-12-11)

C:\Users\Orlando>

C:\Users\Orlando>git clone --recursive https://github.com/hashgraph/hedera-sdk-rust.git
Cloning into 'hedera-sdk-rust'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 1886 (delta 18), reused 28 (delta 16), pack-reused 1848
Receiving objects: 100% (1886/1886), 420.53 KiB | 2.27 MiB/s, done.
Resolving deltas: 100% (1318/1318), done.

C:\Users\Orlando>cd hedera-sdk-rust

C:\Users\Orlando\hedera-sdk-rust>cargo build
C:\Users\Orlando\hedera-sdk-rust>cargo build
    Updating git repository `https://github.com/QuestofIranon/bip39-rs.git`
    Updating crates.io index
  Downloaded query_interface v0.3.5
  Downloaded tokio-async-await v0.1.4
  Downloaded ed25519-dalek v1.0.0-pre.0
  Downloaded log v0.4.6
  Downloaded once_cell v0.1.6
  Downloaded num v0.2.0
  Downloaded futures-preview v0.3.0-alpha.10
  Downloaded rand_chacha v0.1.0
  Downloaded itertools v0.8.0
  Downloaded rand v0.6.1
  Downloaded futures v0.1.25
  Downloaded failure_derive v0.1.3
  Downloaded failure v0.1.3
  Downloaded parking_lot v0.7.0
  Downloaded grpc v0.6.1
  Downloaded try_from v0.3.2
  Downloaded hex v0.3.2
  Downloaded tokio v0.1.13
  Downloaded chrono v0.4.6
  Downloaded pbkdf2 v0.3.0
  Downloaded protoc-rust-grpc v0.6.1
  Downloaded hmac v0.7.0
  Downloaded glob v0.2.11
  Downloaded hashbrown v0.1.7
  Downloaded simple_asn1 v0.3.0
  Downloaded httpbis v0.7.0
  Downloaded cfg-if v0.1.6
  Downloaded protobuf v2.2.0
  Downloaded num-bigint v0.2.2
  Downloaded rustc_version v0.2.3
  Downloaded rand_core v0.3.0
  Downloaded futures-executor-preview v0.3.0-alpha.10
  Downloaded rand_isaac v0.1.1
  Downloaded parking_lot v0.6.4
  Downloaded sha2 v0.8.0
  Downloaded futures-util-preview v0.3.0-alpha.10
  Downloaded winapi v0.3.6
  Downloaded byteorder v1.2.7
  Downloaded crypto-mac v0.7.0
  Downloaded futures-cpupool v0.1.8
  Downloaded tokio-tls-api v0.1.20
  Downloaded tokio-fs v0.1.4
  Downloaded tokio-codec v0.1.1
  Downloaded tokio-threadpool v0.1.9
  Downloaded tokio-executor v0.1.5
  Downloaded tokio-reactor v0.1.7
  Downloaded num-traits v0.2.6
  Downloaded num-iter v0.1.37
  Downloaded num-integer v0.1.39
  Downloaded futures-sink-preview v0.3.0-alpha.10
  Downloaded synstructure v0.10.1
  Downloaded proc-macro2 v0.4.24
  Downloaded either v1.5.0
  Downloaded rand v0.5.5
  Downloaded syn v0.15.23
  Downloaded futures-core-preview v0.3.0-alpha.10
  Downloaded rayon v1.0.3
  Downloaded curve25519-dalek v1.0.1
  Downloaded tokio-io v0.1.10
  Downloaded tls-api v0.1.20
  Downloaded tokio-core v0.1.17
  Downloaded bytes v0.4.11
  Downloaded parking_lot_core v0.4.0
  Downloaded tls-api-stub v0.1.20
  Downloaded tokio-current-thread v0.1.4
  Downloaded tokio-udp v0.1.3
  Downloaded num_cpus v1.9.0
  Downloaded lock_api v0.1.5
  Downloaded tokio-timer v0.2.8
  Downloaded tempdir v0.3.7
  Downloaded protoc v2.2.0
  Downloaded mio v0.6.16
  Downloaded futures-io-preview v0.3.0-alpha.10
  Downloaded rand_xorshift v0.1.0
  Downloaded quote v0.6.10
  Downloaded backtrace v0.3.13
  Downloaded scopeguard v0.3.3
  Downloaded clear_on_drop v0.2.3
  Downloaded base64 v0.9.3
  Downloaded time v0.1.41
  Downloaded grpc-compiler v0.6.1
  Downloaded protoc-rust v2.2.0
  Downloaded num-complex v0.2.1
  Downloaded num-rational v0.2.1
  Downloaded tokio-tcp v0.1.2
  Downloaded digest v0.8.0
  Downloaded rand_hc v0.1.0
  Downloaded void v1.0.2
  Downloaded tokio-timer v0.1.2
  Downloaded scoped-tls v0.1.2
  Downloaded lazycell v1.2.1
  Downloaded lazy_static v1.2.0
  Downloaded net2 v0.2.33
  Downloaded libc v0.2.45
  Downloaded pin-utils v0.1.0-alpha.3
  Downloaded unicode-xid v0.1.0
  Downloaded rand_pcg v0.1.1
  Downloaded cc v1.0.26
  Downloaded safemem v0.3.0
  Downloaded remove_dir_all v0.5.1
  Downloaded futures-channel-preview v0.3.0-alpha.10
  Downloaded miow v0.2.1
  Downloaded kernel32-sys v0.2.2
  Downloaded winapi v0.2.8
  Downloaded rand_core v0.2.2
  Downloaded opaque-debug v0.2.1
  Downloaded autocfg v0.1.1
  Downloaded rayon-core v1.4.1
  Downloaded subtle v1.0.0
  Downloaded generic-array v0.12.0
  Downloaded subtle v2.0.0
  Downloaded rand v0.4.3
  Downloaded slab v0.4.1
  Downloaded rustc-demangle v0.1.10
  Downloaded parking_lot_core v0.3.1
  Downloaded owning_ref v0.4.0
  Downloaded semver v0.9.0
  Downloaded fake-simd v0.1.2
  Downloaded smallvec v0.6.7
  Downloaded protobuf-codegen v2.2.0
  Downloaded iovec v0.1.2
  Downloaded crossbeam-deque v0.2.0
  Downloaded block-buffer v0.7.0
  Downloaded winapi-build v0.1.1
  Downloaded ws2_32-sys v0.2.1
  Downloaded semver-parser v0.7.0
  Downloaded stable_deref_trait v1.1.1
  Downloaded typenum v1.10.0
  Downloaded slab v0.3.0
  Downloaded unreachable v1.0.0
  Downloaded block-padding v0.1.2
  Downloaded crossbeam-utils v0.2.2
  Downloaded crossbeam-epoch v0.3.1
  Downloaded byte-tools v0.3.0
  Downloaded crossbeam-deque v0.6.2
  Downloaded crossbeam-utils v0.6.3
  Downloaded memoffset v0.2.1
  Downloaded nodrop v0.1.13
  Downloaded arrayvec v0.4.8
  Downloaded crossbeam-epoch v0.6.1
   Compiling semver-parser v0.7.0
   Compiling winapi v0.3.6
   Compiling winapi-build v0.1.1
   Compiling void v1.0.2
   Compiling rand_core v0.3.0
   Compiling stable_deref_trait v1.1.1
   Compiling winapi v0.2.8
   Compiling cfg-if v0.1.6
   Compiling libc v0.2.45
   Compiling nodrop v0.1.13
   Compiling lazy_static v1.2.0
   Compiling scopeguard v0.3.3
   Compiling memoffset v0.2.1
   Compiling byteorder v1.2.7
   Compiling proc-macro2 v0.4.24
   Compiling lazycell v1.2.1
   Compiling slab v0.4.1
   Compiling typenum v1.10.0
   Compiling futures v0.1.25
   Compiling protobuf v2.2.0
   Compiling unicode-xid v0.1.0
   Compiling cc v1.0.26
   Compiling either v1.5.0
   Compiling num-traits v0.2.6
   Compiling num-integer v0.1.39
   Compiling rayon-core v1.4.1
   Compiling autocfg v0.1.1
   Compiling byte-tools v0.3.0
   Compiling failure_derive v0.1.3
   Compiling scoped-tls v0.1.2
   Compiling num-bigint v0.2.2
   Compiling rayon v1.0.3
   Compiling subtle v2.0.0
   Compiling num-complex v0.2.1
   Compiling httpbis v0.7.0
   Compiling num-iter v0.1.37
   Compiling subtle v1.0.0
   Compiling pin-utils v0.1.0-alpha.3
   Compiling rustc-demangle v0.1.10
   Compiling num-rational v0.2.1
   Compiling slab v0.3.0
   Compiling safemem v0.3.0
   Compiling glob v0.2.11
   Compiling fake-simd v0.1.2
   Compiling opaque-debug v0.2.1
   Compiling query_interface v0.3.5
   Compiling hex v0.3.2
   Compiling crossbeam-utils v0.6.3
   Compiling log v0.4.6
   Compiling crossbeam-utils v0.2.2
   Compiling try_from v0.3.2
   Compiling owning_ref v0.4.0
   Compiling unreachable v1.0.0
   Compiling arrayvec v0.4.8
   Compiling kernel32-sys v0.2.2
   Compiling ws2_32-sys v0.2.1
   Compiling rand_core v0.2.2
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.0
   Compiling semver v0.9.0
   Compiling hashbrown v0.1.7
   Compiling futures-core-preview v0.3.0-alpha.10
   Compiling itertools v0.8.0
   Compiling block-padding v0.1.2
   Compiling backtrace v0.3.13
   Compiling clear_on_drop v0.2.3
   Compiling tokio-executor v0.1.5
   Compiling base64 v0.9.3
   Compiling tokio-timer v0.1.2
   Compiling protoc v2.2.0
   Compiling tls-api v0.1.20
   Compiling lock_api v0.1.5
   Compiling smallvec v0.6.7
   Compiling crossbeam-epoch v0.6.1
   Compiling crossbeam-epoch v0.3.1
   Compiling rustc_version v0.2.3
   Compiling futures-channel-preview v0.3.0-alpha.10
   Compiling tls-api-stub v0.1.20
   Compiling tokio-timer v0.2.8
   Compiling tokio-current-thread v0.1.4
   Compiling num_cpus v1.9.0
   Compiling crossbeam-deque v0.6.2
   Compiling crossbeam-deque v0.2.0
   Compiling rand_pcg v0.1.1
   Compiling parking_lot_core v0.3.1
   Compiling rand_chacha v0.1.0
   Compiling rand v0.6.1
   Compiling parking_lot_core v0.4.0
   Compiling generic-array v0.12.0
   Compiling futures-sink-preview v0.3.0-alpha.10
   Compiling quote v0.6.10
   Compiling futures-cpupool v0.1.8
   Compiling digest v0.8.0
   Compiling block-buffer v0.7.0
   Compiling crypto-mac v0.7.0
   Compiling syn v0.15.23
   Compiling sha2 v0.8.0
   Compiling hmac v0.7.0
   Compiling rand v0.5.5
   Compiling net2 v0.2.33
   Compiling rand v0.4.3
   Compiling remove_dir_all v0.5.1
   Compiling time v0.1.41
   Compiling tempdir v0.3.7
   Compiling pbkdf2 v0.3.0
   Compiling tokio-threadpool v0.1.9
   Compiling curve25519-dalek v1.0.1
   Compiling chrono v0.4.6
   Compiling num v0.2.0
   Compiling parking_lot v0.6.4
   Compiling parking_lot v0.7.0
   Compiling synstructure v0.10.1
   Compiling once_cell v0.1.6
   Compiling simple_asn1 v0.3.0
   Compiling failure v0.1.3
   Compiling ed25519-dalek v1.0.0-pre.0
   Compiling bip39 v0.5.1 (https://github.com/QuestofIranon/bip39-rs.git#9142cf80)
   Compiling iovec v0.1.2
   Compiling miow v0.2.1
   Compiling bytes v0.4.11
   Compiling futures-io-preview v0.3.0-alpha.10
   Compiling futures-util-preview v0.3.0-alpha.10
   Compiling mio v0.6.16
   Compiling tokio-io v0.1.10
   Compiling tokio-codec v0.1.1
   Compiling tokio-async-await v0.1.4
   Compiling tokio-fs v0.1.4
   Compiling tokio-reactor v0.1.7
   Compiling futures-executor-preview v0.3.0-alpha.10
   Compiling tokio-tcp v0.1.2
   Compiling tokio-udp v0.1.3
   Compiling futures-preview v0.3.0-alpha.10
   Compiling tokio v0.1.13
   Compiling tokio-core v0.1.17
   Compiling tokio-tls-api v0.1.20
   Compiling protobuf-codegen v2.2.0
   Compiling grpc v0.6.1
   Compiling grpc-compiler v0.6.1
   Compiling protoc-rust v2.2.0
   Compiling protoc-rust-grpc v0.6.1
   Compiling hedera v0.3.1-alpha.0 (C:\Users\Orlando\hedera-sdk-rust)
error: failed to run custom build command for `hedera v0.3.1-alpha.0 (C:\Users\Orlando\hedera-sdk-rust)`
process didn't exit successfully: `C:\Users\Orlando\hedera-sdk-rust\target\debug\build\hedera-ac426a9bd1ca53c7\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'protoc version: Custom { kind: NotFound, error: StringError("failed to spawn `\"protoc\" \"--version\"`: The system cannot find the file specified. (os error 2)") }', src\libcore\result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

C:\Users\Orlando\hedera-sdk-rust>
C:\Users\Orlando\hedera-sdk-rust>set RUST_BACKTRACE=1

C:\Users\Orlando\hedera-sdk-rust>cargo build
   Compiling hedera v0.3.1-alpha.0 (C:\Users\Orlando\hedera-sdk-rust)
error: failed to run custom build command for `hedera v0.3.1-alpha.0 (C:\Users\Orlando\hedera-sdk-rust)`
process didn't exit successfully: `C:\Users\Orlando\hedera-sdk-rust\target\debug\build\hedera-ac426a9bd1ca53c7\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'protoc version: Custom { kind: NotFound, error: StringError("failed to spawn `\"protoc\" \"--version\"`: The system cannot find the file specified. (os error 2)") }', src\libcore\result.rs:1009:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys::windows::backtrace::set_frames
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\sys\windows\backtrace\mod.rs:104
   3: std::sys_common::backtrace::print
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\sys_common\backtrace.rs:59
   4: std::sys_common::backtrace::print
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\sys_common\backtrace.rs:59
   5: std::panicking::default_hook
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\panicking.rs:225
   6: std::panicking::rust_panic_with_hook
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\panicking.rs:488
   7: std::panicking::continue_panic_fmt
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\panicking.rs:395
   8: std::panicking::rust_begin_panic
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\panicking.rs:322
   9: core::panicking::panic_fmt
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libcore\panicking.rs:95
  10: core::result::unwrap_failed<std::io::error::Error>
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\src\libcore\macros.rs:26
  11: core::result::Result<protoc::Version, std::io::error::Error>::expect<protoc::Version,std::io::error::Error>
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\src\libcore\result.rs:835
  12: protoc_rust_grpc::run
             at C:\Users\Orlando\.cargo\registry\src\github.com-1ecc6299db9ec823\protoc-rust-grpc-0.6.1\src\lib.rs:31
  13: build_script_build::main
             at .\build.rs:10
  14: std::rt::lang_start::{{closure}}<()>
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\src\libstd\rt.rs:74
  15: std::rt::lang_start_internal::{{closure}}
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\rt.rs:59
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\rt.rs:59
  17: panic_unwind::__rust_maybe_catch_panic
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libpanic_unwind\lib.rs:102
  18: std::panicking::try
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\panicking.rs:286
  19: std::panicking::try
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\panicking.rs:286
  20: std::panicking::try
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\/src\libstd\panicking.rs:286
  21: std::rt::lang_start<()>
             at /rustc/96d1334e567237b1507cd277938e7ae2de75ff51\src\libstd\rt.rs:74
  22: main
  23: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  25: BaseThreadInitThunk
  26: RtlUserThreadStart

C:\Users\Orlando\hedera-sdk-rust>

**Comment by mehcode** [comment]
```
thread 'main' panicked at 'protoc version: Custom { kind: NotFound, error: StringError("failed to spawn \"protoc\" \"--version\": The system cannot find the file specified. (os error 2)") }', src\libcore\result.rs:1009:5
```

You want to grab the protobuf compiler (protoc) [from Google](https://developers.google.com/protocol-buffers/docs/downloads). I would recommend using [scoop](https://scoop.sh) here as it makes windows dev a lot easier to deal with.

```
$ scoop install rustup
$ scoop install protobuf
```

**Comment by orlcp440** [comment]
Just wanted to add that I had to install protobuf manually because scoop on Windows could not find that package.

**Comment by mehcode** [comment]
Ah. You probably needed to activate the extras bundle. I forget I have that activated. 

https://github.com/lukesampson/scoop-extras
