### ISSUE TITLE
testnet defaults to node account 0.0.3

### ISSUE THREAD

**Issue by tim-mchale** [launchbadge/hedera-sdk-rust-archived#70]
Lines 114 to 123 of `client.rs` assume that testnets will always use node account `0.0.3`

While this may be true currently, it may be misleading in future. Although convenient right now, I suggest that this code is superfluous. All examples show code setting node accounts explicitly.

Can we remove this?

**Comment by mehcode** [comment]
Node accounts are going to always be tied 1-1 to a node `address`. 

There are a tiny number of test nodes currently and that will get smaller in the future if I guess correctly.

Further, we should be doing this for main nodes as well. There aren't going to be a lot of those either.

My point is this is the kind of configuration that the SDK should really be able to know. If it eventually has to ask the node for it's ID first, it can do that and cache it.

**Comment by tim-mchale** [comment]
Perhaps, but not always the _same_ address. It is possible that future node "owners" will run multiple nodes and choose to use a single account to pool all node payments. Different node owners will definitely user different node accounts. Either way, this code is based upon assumptions that may or may not prove to be correct in the future. As it stands, the code only applies to testnets, and makes the assumption that only one node (API endpoint) is present in each testnet. This will undoubtedly change in the future. Removing this code forces SDK users to explicitly specify the node account, which is probably a good habit for them to form. Each subsidiary SDK already implements the ability to default that node account until subsequent change is necessary and/or manually specify in each case.
